import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'Cubeforge',
  description: 'React-first 2D browser game engine',
  appearance: true,
  base: '/',
  themeConfig: {
    logo: '/logo.svg',
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'API', link: '/api/game' },
      { text: 'Examples', link: 'https://play.cubeforge.dev' },
      { text: 'Editor', link: 'https://editor.cubeforge.dev' },
      { text: 'GitHub', link: 'https://github.com/1homsi/cubeforge' },
    ],
    sidebar: {
      '/guide/': [
        {
          text: 'Introduction',
          items: [
            { text: 'What is Cubeforge?', link: '/guide/what-is-cubeforge' },
            { text: 'Getting Started', link: '/guide/getting-started' },
          ],
        },
        {
          text: 'Core Concepts',
          items: [
            { text: 'ECS', link: '/guide/ecs' },
            { text: 'Physics', link: '/guide/physics' },
            { text: 'Rendering', link: '/guide/rendering' },
            { text: 'Input', link: '/guide/input' },
            { text: 'Tilemaps', link: '/guide/tilemaps' },
          ],
        },
        {
          text: 'Advanced',
          items: [
            { text: 'DevTools & Deterministic Mode', link: '/guide/devtools' },
            { text: 'Renderer (WebGL2)', link: '/guide/renderer' },
            { text: 'Data-Driven Games', link: '/guide/data-driven-games' },
            { text: 'Performance', link: '/guide/performance' },
            { text: 'Migration Guide', link: '/guide/migration' },
            { text: 'Multiplayer', link: '/guide/multiplayer' },
            { text: 'Hot Module Replacement', link: '/guide/hmr' },
            { text: 'Embedding in React Apps', link: '/guide/embedding' },
          ],
        },
      ],
      '/api/': [
        {
          text: 'Components',
          items: [
            { text: 'Game', link: '/api/game' },
            { text: 'World', link: '/api/world' },
            { text: 'Entity', link: '/api/entity' },
            { text: 'Transform', link: '/api/transform' },
            { text: 'Sprite', link: '/api/sprite' },
            { text: 'Text', link: '/api/text' },
            { text: 'RigidBody', link: '/api/rigidbody' },
            { text: 'BoxCollider', link: '/api/boxcollider' },
            { text: 'CircleCollider', link: '/api/circle-collider' },
            { text: 'CapsuleCollider', link: '/api/capsule-collider' },
            { text: 'Script', link: '/api/script' },
            { text: 'Camera2D', link: '/api/camera2d' },
            { text: 'CameraZone', link: '/api/camera-zone' },
            { text: 'Animation', link: '/api/animation' },
            { text: 'AnimatedSprite', link: '/api/animated-sprite' },
            { text: 'Animator', link: '/api/animator' },
            { text: 'Trail', link: '/api/trail' },
            { text: 'ParticleEmitter', link: '/api/particle-emitter' },
            { text: 'SquashStretch', link: '/api/squash-stretch' },
            { text: 'ParallaxLayer', link: '/api/parallax-layer' },
            { text: 'MovingPlatform', link: '/api/moving-platform' },
            { text: 'Checkpoint', link: '/api/checkpoint' },
            { text: 'Tilemap', link: '/api/tilemap' },
            { text: 'TileLayer', link: '/api/tile-layer' },
            { text: 'SpriteLayer', link: '/api/sprite-layer' },
            { text: 'ScreenFlash', link: '/api/screen-flash' },
            { text: 'VirtualJoystick', link: '/api/virtual-joystick' },
            { text: 'AssetLoader', link: '/api/asset-loader' },
            { text: 'Circle', link: '/api/circle' },
            { text: 'Line', link: '/api/line' },
            { text: 'Polygon', link: '/api/polygon' },
            { text: 'Joint', link: '/api/joint' },
            { text: 'Mask', link: '/api/mask' },
            { text: 'Gradient', link: '/api/gradient' },
            { text: 'NineSlice', link: '/api/nine-slice' },
            { text: 'CompoundCollider', link: '/api/compound-collider' },
          ],
        },
        {
          text: 'Hooks',
          items: [
            { text: 'usePlatformerController', link: '/api/use-platformer-controller' },
            { text: 'useTopDownMovement', link: '/api/use-top-down-movement' },
            { text: 'useGame', link: '/api/use-game' },
            { text: 'useEntity', link: '/api/use-entity' },
            { text: 'useDestroyEntity', link: '/api/use-destroy-entity' },
            { text: 'useHealth', link: '/api/use-health' },
            { text: 'useDamageZone', link: '/api/use-damage-zone' },
            { text: 'useAnimationController', link: '/api/use-animation-controller' },
            { text: 'usePersistedBindings', link: '/api/use-persisted-bindings' },
            { text: 'useVirtualInput', link: '/api/virtual-joystick' },
            { text: 'useInput', link: '/api/use-input' },
            { text: 'useInputMap', link: '/api/use-input-map' },
            { text: 'useInputContext', link: '/api/use-input-context' },
            { text: 'usePlayerInput', link: '/api/use-player-input' },
            { text: 'useLocalMultiplayer', link: '/api/use-local-multiplayer' },
            { text: 'useInputRecorder', link: '/api/use-input-recorder' },
            { text: 'useCamera', link: '/api/use-camera' },
            { text: 'useCoordinates', link: '/api/use-coordinates' },
            { text: 'useEvent', link: '/api/use-event' },
            { text: 'useTriggerEnter / useTriggerExit', link: '/api/use-trigger' },
            { text: 'useCollisionEnter / useCollisionExit', link: '/api/use-collision' },
            { text: 'useCircleEnter / useCircleExit', link: '/api/use-circle' },
            { text: 'useCollidingWith', link: '/api/use-colliding-with' },
            { text: 'useKinematicBody', link: '/api/use-kinematic-body' },
            { text: 'useDropThrough', link: '/api/use-drop-through' },
            { text: 'useSound', link: '/api/use-sound' },
            { text: 'useMusic', link: '/api/use-music' },
            { text: 'useStreamedMusic', link: '/api/use-streamed-music' },
            { text: 'useSpatialSound', link: '/api/use-spatial-sound' },
            { text: 'useAudioAnalyser', link: '/api/use-audio-analyser' },
            { text: 'useAudioScheduler', link: '/api/use-audio-scheduler' },
            { text: 'usePreloadAudio', link: '/api/use-preload-audio' },
            { text: 'useGamepad', link: '/api/use-gamepad' },
            { text: 'usePause', link: '/api/use-pause' },
            { text: 'usePreload', link: '/api/use-preload' },
            { text: 'useSave', link: '/api/use-save' },
            { text: 'usePathfinding', link: '/api/use-pathfinding' },
            { text: 'useAISteering', link: '/api/use-ai-steering' },
            { text: 'useLevelTransition', link: '/api/use-level-transition' },
            { text: 'useGameStateMachine', link: '/api/use-game-state-machine' },
            { text: 'useRestart', link: '/api/use-restart' },
            { text: 'useSnapshot', link: '/api/use-snapshot' },
            { text: 'useTween', link: '/api/use-tween' },
            { text: 'useProfiler', link: '/api/use-profiler' },
            { text: 'useObjectPool', link: '/api/use-object-pool' },
            { text: 'usePostProcess', link: '/api/post-processing' },
            { text: 'useTimer', link: '/api/use-timer' },
            { text: 'useCoroutine', link: '/api/use-coroutine' },
            { text: 'useSceneManager', link: '/api/use-scene-manager' },
            { text: 'useTouch', link: '/api/use-touch' },
            { text: 'useInputBuffer', link: '/api/use-input-buffer' },
            { text: 'useComboDetector', link: '/api/use-combo-detector' },
            { text: 'useAccessibility', link: '/api/use-accessibility' },
            { text: 'useHMR', link: '/api/use-hmr' },
            { text: 'useParent', link: '/api/use-parent' },
            { text: 'useGameStore', link: '/api/use-game-store' },
            { text: 'useDialogue', link: '/api/use-dialogue' },
            { text: 'useCutscene', link: '/api/use-cutscene' },
          ],
        },
        {
          text: 'Effects',
          items: [
            { text: 'Post-Processing', link: '/api/post-processing' },
          ],
        },
        {
          text: 'Utilities',
          items: [
            { text: 'tween', link: '/api/tween' },
            { text: 'createAtlas', link: '/api/create-atlas' },
            { text: 'createInputMap', link: '/api/create-input-map' },
            { text: 'findByTag', link: '/api/find-by-tag' },
            { text: 'Spatial Queries', link: '/api/spatial-queries' },
            { text: 'createTimer', link: '/api/create-timer' },
            { text: 'Audio Groups', link: '/api/audio-groups' },
            { text: 'Audio Settings', link: '/api/audio-settings' },
            { text: 'createWebSocketTransport', link: '/api/create-web-socket-transport' },
            { text: 'createWebRTCTransport', link: '/api/create-web-rtc-transport' },
            { text: 'InterpolationBuffer', link: '/api/interpolation-buffer' },
            { text: 'definePlugin', link: '/api/define-plugin' },
            { text: 'defineAnimations', link: '/api/define-animations' },
            { text: 'sweepBox', link: '/api/sweep-box' },
            { text: 'createCompoundCollider', link: '/api/create-compound-collider' },
            { text: 'SpatialHash', link: '/api/spatial-hash' },
            { text: 'Hierarchy', link: '/api/hierarchy' },
            { text: 'Steering Helpers', link: '/api/steering-helpers' },
            { text: 'mergeTileColliders', link: '/api/merge-tile-colliders' },
            { text: 'raycastAll', link: '/api/raycast-all' },
            { text: 'overlapCircle', link: '/api/overlap-circle' },
            { text: 'createTimeline', link: '/api/create-timeline' },
            { text: 'createJoint', link: '/api/create-joint' },
            { text: 'playClip / setAnimationState', link: '/api/play-clip' },
            { text: 'definePrefab', link: '/api/define-prefab' },
          ],
        },
      ],
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/1homsi/cubeforge' },
    ],
    search: { provider: 'local' },
    footer: {
      message: 'MIT License',
      copyright: 'Copyright © 2025 1homsi - Built by <a href="https://voxire.com" target="_blank">Voxire</a>',
    },
  },
})
